### ISSUE TITLE
Error running Nomadnet on Raspberry Pi

### ISSUE THREAD

**Issue by KenSamson** [markqvist/NomadNet#63]
**Describe the Bug**
Error launching nomadnet - details below

**To Reproduce**
(general) radiomanalpha@raspberrypi:~ $ nomadnet --version
Nomad Network Client 0.5.6
(general) radiomanalpha@raspberrypi:~ $ rns --version
bash: rns: command not found
(general) radiomanalpha@raspberrypi:~ $ rnsd --version
rnsd 0.8.8
(general) radiomanalpha@raspberrypi:~ $ nomadnet
[2024-12-16 13:54:22] [Debug] Started shared instance interface: Shared Instance[37428]
[2024-12-16 13:54:22] [Debug] Cleaning ratchets...
[2024-12-16 13:54:22] [Verbose] Bringing up system interfaces...
[2024-12-16 13:54:22] [Debug] Skipping disabled interface "Default Interface"
[2024-12-16 13:54:22] [Debug] Establishing TCP connection for TCPInterface[TCP Client Interface/pi.kcmo.net:31313]...
[2024-12-16 13:54:22] [Debug] TCP connection for TCPInterface[TCP Client Interface/pi.kcmo.net:31313] established
[2024-12-16 13:54:22] [Notice] Opening serial port /dev/serial/by-id/usb-1a86_USB_Single_Serial_5887032285-if00...
[2024-12-16 13:54:24] [Notice] Serial port /dev/serial/by-id/usb-1a86_USB_Single_Serial_5887032285-if00 is now open
[2024-12-16 13:54:24] [Verbose] Configuring RNode interface...
[2024-12-16 13:54:24] [Verbose] Waiting for radio configuration validation for RNodeInterface[RNode LoRa Interface]...
[2024-12-16 13:54:24] [Debug] RNodeInterface[RNode LoRa Interface] Radio reporting frequency is 905.0 MHz
[2024-12-16 13:54:24] [Debug] RNodeInterface[RNode LoRa Interface] Radio reporting symbol time is 0.51ms (at 1953 baud)
[2024-12-16 13:54:24] [Debug] RNodeInterface[RNode LoRa Interface] Radio reporting preamble is 30 symbols (15ms)
[2024-12-16 13:54:24] [Debug] RNodeInterface[RNode LoRa Interface] Radio reporting CSMA slot time is 50ms
[2024-12-16 13:54:24] [Debug] RNodeInterface[RNode LoRa Interface] Radio reporting bandwidth is 500.0 KHz
[2024-12-16 13:54:24] [Debug] RNodeInterface[RNode LoRa Interface] Radio reporting TX power is 7 dBm
[2024-12-16 13:54:24] [Debug] RNodeInterface[RNode LoRa Interface] Radio reporting spreading factor is 8
[2024-12-16 13:54:24] [Debug] RNodeInterface[RNode LoRa Interface] Radio reporting coding rate is 6
[2024-12-16 13:54:24] [Verbose] RNodeInterface[RNode LoRa Interface] On-air bitrate is now 10.42 kbps
[2024-12-16 13:54:25] [Notice] RNodeInterface[RNode LoRa Interface] is configured and powered up
[2024-12-16 13:54:25] [Verbose] System interfaces are ready
[2024-12-16 13:54:25] [Verbose] Utilising cryptography backend "openssl, PyCA 43.0.1"
[2024-12-16 13:54:25] [Verbose] Configuration loaded from /home/radiomanalpha/.reticulum/config
[2024-12-16 13:54:25] [Verbose] Loaded 384 known destination from storage
[2024-12-16 13:54:25] [Verbose] Loaded Transport Identity from storage
[2024-12-16 13:54:25] [Debug] Loaded path table entry for <0ea474ff99e634e555745131cf2cd7da> from storage
[2024-12-16 13:54:25] [Debug] Loaded path table entry for <056b052c847ccee634a5b98de1dc7d05> from storage
[2024-12-16 13:54:25] [Debug] Loaded path table entry for <09641c73203180548552bf72c70d2d33> from storage
[2024-12-16 13:54:25] [Debug] Loaded path table entry for <56a259df8c7b2feb6e6356002954ba7f> from storage
[2024-12-16 13:54:25] [Debug] Loaded path table entry for <4fb4a05cbae9aae31d19c82c954e7663> from storage
[2024-12-16 13:54:25] [Debug] Loaded path table entry for <cadd0c5d6fe7fa722457d592e350a60d> from storage
[2024-12-16 13:54:25] [Debug] Loaded path table entry for <2825f4ba345c4554b846e2ba6a05dbe5> from storage
[2024-12-16 13:54:25] [Debug] Loaded path table entry for <abe8771b034bff2a6cde1ec3e4cf8938> from storage
[2024-12-16 13:54:25] [Verbose] Loaded 8 path table entries from storage
[2024-12-16 13:54:25] [Verbose] Loaded 0 tunnel table entries from storage
[2024-12-16 13:54:25] [Verbose] Transport instance <7631edb93e574aaf7aad8ced53a1a76a> started
Traceback (most recent call last):
  File "/home/radiomanalpha/general/bin/nomadnet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/radiomanalpha/general/lib/python3.11/site-packages/nomadnet/nomadnet.py", line 51, in main
    program_setup(configarg, rnsconfigarg, daemon, console)
  File "/home/radiomanalpha/general/lib/python3.11/site-packages/nomadnet/nomadnet.py", line 11, in program_setup
    app = nomadnet.NomadNetworkApp(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/radiomanalpha/general/lib/python3.11/site-packages/nomadnet/NomadNetworkApp.py", line 293, in __init__
    self.message_router = LXMF.LXMRouter(
                          ^^^^^^^^^^^^^^
AttributeError: module 'LXMF' has no attribute 'LXMRouter'

As this almost looks like this is a config issue, I've attached both the RNS and Nomadnet config files
[nomadnet.config.txt](https://github.com/user-attachments/files/18156591/nomadnet.config.txt)
[reticulum.confg.txt](https://github.com/user-attachments/files/18156592/reticulum.confg.txt)

**Comment by KenSamson** [comment]
Uninstalled and re-installed lxmf, and sideband now runs.. thanks for looking...

Please close...
